targets:
  $default:
    builders:
      json_serializable:
        options:
          # Use explicit nullable types
          explicit_to_json: true
          # Include JSON keys in field names
          include_if_null: false 