name: random_mtg_card
description: >-
  Cross-platform MTG card display app with comprehensive filtering, favorites,
  and gesture navigation
publish_to: none
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  json_annotation: ^4.8.1
  cached_network_image: ^3.3.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  window_manager: ^0.3.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.0
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  http_mock_adapter: ^0.6.0
  test: ^1.24.0
  platform: ^3.1.0
  fake_async: ^1.3.1
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
platforms:
  windows:
    plugins:
      window_manager:
        path: packages/window_manager
  macos:
    plugins:
      window_manager:
        path: packages/window_manager
  linux:
    plugins:
      window_manager:
        path: packages/window_manager
